#!/usr/bin/env python3
"""Generates trace_tables.h (method lists, counting stubs, export forwarders) and
d3d9trace.def for d3d9trace.cpp. The method order is checked against d3d9.h at
compile time (static_assert on offsetof), so a typo here fails the build."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
DEV = """QueryInterface AddRef Release TestCooperativeLevel GetAvailableTextureMem EvictManagedResources
GetDirect3D GetDeviceCaps GetDisplayMode GetCreationParameters SetCursorProperties SetCursorPosition
ShowCursor CreateAdditionalSwapChain GetSwapChain GetNumberOfSwapChains Reset Present GetBackBuffer
GetRasterStatus SetDialogBoxMode SetGammaRamp GetGammaRamp CreateTexture CreateVolumeTexture
CreateCubeTexture CreateVertexBuffer CreateIndexBuffer CreateRenderTarget CreateDepthStencilSurface
UpdateSurface UpdateTexture GetRenderTargetData GetFrontBufferData StretchRect ColorFill
CreateOffscreenPlainSurface SetRenderTarget GetRenderTarget SetDepthStencilSurface GetDepthStencilSurface
BeginScene EndScene Clear SetTransform GetTransform MultiplyTransform SetViewport GetViewport SetMaterial
GetMaterial SetLight GetLight LightEnable GetLightEnable SetClipPlane GetClipPlane SetRenderState
GetRenderState CreateStateBlock BeginStateBlock EndStateBlock SetClipStatus GetClipStatus GetTexture
SetTexture GetTextureStageState SetTextureStageState GetSamplerState SetSamplerState ValidateDevice
SetPaletteEntries GetPaletteEntries SetCurrentTexturePalette GetCurrentTexturePalette SetScissorRect
GetScissorRect SetSoftwareVertexProcessing GetSoftwareVertexProcessing SetNPatchMode GetNPatchMode
DrawPrimitive DrawIndexedPrimitive DrawPrimitiveUP DrawIndexedPrimitiveUP ProcessVertices
CreateVertexDeclaration SetVertexDeclaration GetVertexDeclaration SetFVF GetFVF CreateVertexShader
SetVertexShader GetVertexShader SetVertexShaderConstantF GetVertexShaderConstantF
SetVertexShaderConstantI GetVertexShaderConstantI SetVertexShaderConstantB GetVertexShaderConstantB
SetStreamSource GetStreamSource SetStreamSourceFreq GetStreamSourceFreq SetIndices GetIndices
CreatePixelShader SetPixelShader GetPixelShader SetPixelShaderConstantF GetPixelShaderConstantF
SetPixelShaderConstantI GetPixelShaderConstantI SetPixelShaderConstantB GetPixelShaderConstantB
DrawRectPatch DrawTriPatch DeletePatch CreateQuery""".split()
D3D = """QueryInterface AddRef Release RegisterSoftwareDevice GetAdapterCount GetAdapterIdentifier
GetAdapterModeCount EnumAdapterModes GetAdapterDisplayMode CheckDeviceType CheckDeviceFormat
CheckDeviceMultiSampleType CheckDepthStencilMatch CheckDeviceFormatConversion GetDeviceCaps
GetAdapterMonitor CreateDevice""".split()
# Every other export of d3d9.dll (Wine's d3d9.spec / Microsoft's): forwarded unchanged.
FWD = ["Direct3DShaderValidatorCreate9", "PSGPError", "PSGPSampleTexture", "D3DPERF_BeginEvent",
       "D3DPERF_EndEvent", "D3DPERF_GetStatus", "D3DPERF_QueryRepeatFrame", "D3DPERF_SetMarker",
       "D3DPERF_SetOptions", "D3DPERF_SetRegion", "DebugSetLevel", "DebugSetMute", "Direct3DCreate9On12",
       "Direct3DCreate9On12Ex", "Direct3D9EnableMaximizedWindowedModeShim"]
assert len(DEV) == 119 and len(D3D) == 17

def stubs(prefix, n):
    lst = ",".join(str(i) for i in range(n))
    return (f'".text\\n"\n'
            f'".irp n,{lst}\\n"\n'
            f'"_{prefix}_stub\\\\n\\\\():\\n"\n'
            f'"  lock incl _g_{prefix}_count+(\\\\n*4)\\n"\n'
            f'"  jmp *_g_{prefix}_orig+(\\\\n*4)\\n"\n'
            f'".endr\\n"\n'
            f'".section .rdata,\\"dr\\"\\n"\n'
            f'".globl _g_{prefix}_stubs\\n"\n'
            f'".p2align 2\\n"\n'
            f'"_g_{prefix}_stubs:\\n"\n'
            f'".irp n,{lst}\\n"\n'
            f'"  .long _{prefix}_stub\\\\n\\n"\n'
            f'".endr\\n"\n'
            f'".text\\n"\n')

out = ["// GENERATED by gen.py — method tables + counting stubs. Do not edit by hand.", "#pragma once", "",
       "#define TRACE_DEV_METHODS(X) " + " ".join(f"X({m})" for m in DEV),
       "#define TRACE_D3D_METHODS(X) " + " ".join(f"X({m})" for m in D3D),
       "#define TRACE_FORWARDS(X) " + " ".join(f"X({m})" for m in FWD),
       f"#define TRACE_DEV_COUNT {len(DEV)}", f"#define TRACE_D3D_COUNT {len(D3D)}",
       f"#define TRACE_FWD_COUNT {len(FWD)}",
       "asm(\n" + stubs("dev", len(DEV)) + stubs("d3d", len(D3D)) + ");",
       "asm(\".text\\n\"\n" + "\n".join(
           f'".globl _fwd_{f}\\n_fwd_{f}:\\n  jmp *_g_fwd_ptr+{i * 4}\\n"' for i, f in enumerate(FWD)) + ");"]
open(os.path.join(HERE, "trace_tables.h"), "w").write("\n".join(out) + "\n")
d = ["LIBRARY d3d9.dll", "EXPORTS", "  Direct3DCreate9=trace_Direct3DCreate9@4",
     "  Direct3DCreate9Ex=trace_Direct3DCreate9Ex@8"] + [f"  {f}=fwd_{f}" for f in FWD]
open(os.path.join(HERE, "d3d9trace.def"), "w").write("\n".join(d) + "\n")
